-- Deploy procedures/immutable_field_trigger to pg


BEGIN;

CREATE FUNCTION immutable_field_trigger()
RETURNS TRIGGER
AS $CODEZ$
BEGIN
  IF TG_NARGS > 0 THEN
    RAISE EXCEPTION 'IMMUTABLE_PROPERTY %', TG_ARGV[0];
  END IF;
  RAISE EXCEPTION 'IMMUTABLE_PROPERTY';
END;
$CODEZ$
LANGUAGE plpgsql;

COMMIT;
