name: LaunchQL Utils tests
on:
  push:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: pyramation/node-sqitch:20.12.0

    env:
      PGHOST: pg_db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
      NODE_OPTIONS: --openssl-legacy-provider
      PYTHON: /usr/bin/python3

    services:
      pg_db:
        image: pyramation/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
 
    steps:
      - name: Configure Git (for tests)
        run: |
          git config --global user.name "CI Test User"
          git config --global user.email "ci@example.com"

      - name: checkout
        uses: actions/checkout@v4

      - name: deps
        run: |
          which python3 || echo "Python3 not found"
          ln -sf $(which python3) /usr/bin/python || echo "Cannot create symlink"
          yarn --ignore-engines
          
      - name: build
        run: |
          PYTHON=/usr/bin/python3 yarn build

      - name: seed app_user
        run: |
          psql -f ./bootstrap-roles.sql postgres
        env:
          PGHOST: pg_db
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password

      - name: utils
        run: cd ./packages/utils && yarn test
        
      - name: totp
        run: cd ./packages/totp && yarn test
      
      - name: jobs
        run: cd ./packages/jobs && yarn test
        
      - name: defaults
        run: cd ./packages/defaults && yarn test
        
      - name: uuid
        run: cd ./packages/uuid && yarn test
        
      - name: verify
        run: cd ./packages/verify && yarn test
        
      - name: types
        run: cd ./packages/types && yarn test
        
      - name: base32
        run: cd ./packages/base32 && yarn test
        
      - name: faker
        run: cd ./packages/faker && yarn test
        
      - name: jwt-claims
        run: cd ./packages/jwt-claims && yarn test
        
      - name: jobs-simple
        run: cd ./packages/jobs-simple && yarn test
        
      - name: measurements
        run: cd ./packages/measurements && yarn test
        
      - name: inflection
        run: cd ./packages/inflection && yarn test
        
      - name: default-roles
        run: cd ./packages/default-roles && yarn test
        
      - name: geotypes
        run: cd ./packages/geotypes && yarn test
        
      - name: stamps
        run: cd ./packages/stamps && yarn test
        
      - name: achievements
        run: cd ./packages/achievements && yarn test
